 - name: Install OpenJDK
   yum: name=java-{{ java_version }}-openjdk state=present
   become: yes

 - name: Copy Java environment setup template
   template: src=env.j2 dest=/etc/profile.d/java.sh owner=root group=root mode=0755
 
 - name: Ensures /opt/apps dir exists
   file: path="/opt/apps" state=directory  

 - name: Copy the credentials and secure it
   copy:
    src: credentials.yaml
    dest: /opt/apps/credentials.yml
    owner: root
    group: root
    mode: 0644