 - name: Install OpenJDK
   yum: name=java-{{ java_version }}-openjdk state=present
   become: yes

 - name: Copy Java environment setup template
   template: src=env.j2 dest=/etc/profile.d/java.sh owner=root group=root mode=0755